### PR TITLE
Simplified Chinese Edit

### PR DESCRIPTION
**Pull request by TobbyLALALA**
Hello there!
I'm a Chinese high school student.I have translated this article into Simplified Chinese.
By the way , express my admiration to you! I'm very proud to play a role in this great project!
(>▽<)

### CODE REVIEW

**Comment by popring** [comment]
Hi @ncase , could you please help merge this request? Thank you!

**Comment by ncase** [comment]
Super sorry for not seeing this 4 years ago, @TobbyLALALA ! 🎉  ( I was busy with a Covid-19-related explainer project, and then, uh, mental-health hole for a year)  Thanks @popring for pinging me on this!  Very very belatedly, this PR is merged now.

**Comment by popring** [comment]
> Super sorry for not seeing this 4 years ago, @TobbyLALALA ! 🎉 ( I was busy with a Covid-19-related explainer project, and then, uh, mental-health hole for a year) Thanks @popring for pinging me on this! Very very belatedly, this PR is merged now.

Thank you, but I have found some issues, and I have already fixed them. Could you please merge them again here?

https://github.com/ncase/mental-health/pull/32

**Comment by popring** [comment]
> > Super sorry for not seeing this 4 years ago, @TobbyLALALA ! 🎉 ( I was busy with a Covid-19-related explainer project, and then, uh, mental-health hole for a year) Thanks @popring for pinging me on this! Very very belatedly, this PR is merged now.
> 
> Thank you, but I have found some issues, and I have already fixed them. Could you please merge them again here?
> 
> #32

@TobbyLALALA Just checking in again on this—thank you so much for your time!

**Pull request merged**
